# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf.proto',
  package='proto_file',
  syntax='proto3',
  serialized_pb=_b('\n\x0eprotobuf.proto\x12\nproto_file\"2\n\navi_return\x12\r\n\x05jobid\x18\x01 \x01(\t\x12\x15\n\rdate_response\x18\x02 \x01(\t\"\x83\x01\n\x06\x65vents\x1aM\n\x04\x64\x61ta\x12\x10\n\x08\x64\x65viceid\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61te_request\x18\x04 \x01(\t\x1a*\n\x08settings\x12\x0f\n\x07subtype\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"0\n\x0e\x63md_to_devices\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\tb\x06proto3')
)




_AVI_RETURN = _descriptor.Descriptor(
  name='avi_return',
  full_name='proto_file.avi_return',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jobid', full_name='proto_file.avi_return.jobid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_response', full_name='proto_file.avi_return.date_response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=80,
)


_EVENTS_DATA = _descriptor.Descriptor(
  name='data',
  full_name='proto_file.events.data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceid', full_name='proto_file.events.data.deviceid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='proto_file.events.data.cmd', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='protocol', full_name='proto_file.events.data.protocol', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_request', full_name='proto_file.events.data.date_request', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=170,
)

_EVENTS_SETTINGS = _descriptor.Descriptor(
  name='settings',
  full_name='proto_file.events.settings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subtype', full_name='proto_file.events.settings.subtype', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto_file.events.settings.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=214,
)

_EVENTS = _descriptor.Descriptor(
  name='events',
  full_name='proto_file.events',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_EVENTS_DATA, _EVENTS_SETTINGS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=214,
)


_CMD_TO_DEVICES = _descriptor.Descriptor(
  name='cmd_to_devices',
  full_name='proto_file.cmd_to_devices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='proto_file.cmd_to_devices.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='proto_file.cmd_to_devices.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=264,
)

_EVENTS_DATA.containing_type = _EVENTS
_EVENTS_SETTINGS.containing_type = _EVENTS
DESCRIPTOR.message_types_by_name['avi_return'] = _AVI_RETURN
DESCRIPTOR.message_types_by_name['events'] = _EVENTS
DESCRIPTOR.message_types_by_name['cmd_to_devices'] = _CMD_TO_DEVICES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

avi_return = _reflection.GeneratedProtocolMessageType('avi_return', (_message.Message,), dict(
  DESCRIPTOR = _AVI_RETURN,
  __module__ = 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:proto_file.avi_return)
  ))
_sym_db.RegisterMessage(avi_return)

events = _reflection.GeneratedProtocolMessageType('events', (_message.Message,), dict(

  data = _reflection.GeneratedProtocolMessageType('data', (_message.Message,), dict(
    DESCRIPTOR = _EVENTS_DATA,
    __module__ = 'protobuf_pb2'
    # @@protoc_insertion_point(class_scope:proto_file.events.data)
    ))
  ,

  settings = _reflection.GeneratedProtocolMessageType('settings', (_message.Message,), dict(
    DESCRIPTOR = _EVENTS_SETTINGS,
    __module__ = 'protobuf_pb2'
    # @@protoc_insertion_point(class_scope:proto_file.events.settings)
    ))
  ,
  DESCRIPTOR = _EVENTS,
  __module__ = 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:proto_file.events)
  ))
_sym_db.RegisterMessage(events)
_sym_db.RegisterMessage(events.data)
_sym_db.RegisterMessage(events.settings)

cmd_to_devices = _reflection.GeneratedProtocolMessageType('cmd_to_devices', (_message.Message,), dict(
  DESCRIPTOR = _CMD_TO_DEVICES,
  __module__ = 'protobuf_pb2'
  # @@protoc_insertion_point(class_scope:proto_file.cmd_to_devices)
  ))
_sym_db.RegisterMessage(cmd_to_devices)


# @@protoc_insertion_point(module_scope)
